# OpenShift Getting Started Workshop

## Overview

|===
|Audience Experience Level
|Beginner

|Average Time to Complete	
|90 minutes
|===

This workshop is intended to give you a hands on introduction to using https://openshift.com[OpenShift] from the perspective of a Developer.

https://www.redhat.com/en/topics/containers/whats-a-linux-container-vb[Containers] are a standardized way to package applications, including all of their dependencies. This simplifies deployment and speeds up delivery. Unlike virtual machines, containers do not bundle to the operating system. Only the application, runtime, libraries, and configuration are packaged inside the container. Thus, containers are more lightweight, portable, and efficient as compared to virtual machines.

For developers looking to kickstart their projets, OpenShift enables efficient application development through streamlined workflows and validated integrations.

### Objectives

* Using the OpenShift command line (CLI) and Web Console.
* Deploying an application using a pre-existing Container Image.
* Working with application Labels to identify component parts.
* Scaling up your application in order to handle web traffic.
* Exposing your application to users outside of the cluster.
* Viewing and working with Logs generated by your application.
* Accessing your application container and interacting with it.
* Giving access to other users to collaborate on your application.
* Deploying an application from Source Code in a Git repository.
* Deploying a Database from the OpenShift Developer Catalog.
* Configuring an application so it can access a database.
* Setting up Web Hooks to enable automated application builds.
* Additional topics may also be covered relevant to the specific programming language used by the applications being deployed.

## Documentation

To test and develop this content locally, you can use a pre-built container with Podman or Docker as shown below.

[source,sh]
----
podman run --rm --name antora -v $PWD:/antora -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

> Note: If using a rootless podman replace `-v $PWD:/antora` with `-v $PWD:/antora:z`

